// <auto-generated />
using AsthmaAlertApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AsthmaAlertApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AsthmaAlertApi.Models.DailyAq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AsthmaCategory");

                    b.Property<int>("AsthmaValue");

                    b.Property<string>("Date");

                    b.Property<string>("DustDanderCategory");

                    b.Property<int>("DustDanderValue");

                    b.Property<int>("Grass");

                    b.Property<int>("Mold");

                    b.Property<string>("OzoneCategory");

                    b.Property<int>("OzoneValue");

                    b.Property<int>("Ragweed");

                    b.Property<int>("Tree");

                    b.HasKey("Id");

                    b.ToTable("DailyAqs");
                });

            modelBuilder.Entity("AsthmaAlertApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("AsthmaAlertApi.Models.TrackingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<int>("HadAttack");

                    b.Property<int>("OwnerId");

                    b.Property<string>("TrackingTitle");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("TrackingItems");
                });

            modelBuilder.Entity("AsthmaAlertApi.Models.TrackingItem", b =>
                {
                    b.HasOne("AsthmaAlertApi.Models.Person", "Owner")
                        .WithMany("TrackingItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
